In [2]:
import torch
from torch import nn
import matplotlib.pyplot as plt

prepare and load data

linear regression

In [3]:
weight = 0.7
bias = 0.3

#create
start = 0
end = 1
step = 0.02
X =  torch.arange(start,end,step).unsqueeze(dim=1)
y = weight * X + bias
X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [4]:
len(X), len(y)

(50, 50)

In [5]:
#create train and test
train_spilit =  int(0.8 * len(X))
X_train, y_train = X[:train_spilit], y[:train_spilit]
X_test, y_test = X[train_spilit:], y[train_spilit:]
len(X_train),len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

building the first linear regression model

این مدل قراره که با مقادیر رندوم وزن و بایاس شروع کنه و هی آپدیت کنه تا به اون مقادیری که دینا را باهاش ساختیم برسه
این کار توسط 2 الگوریتم انجام میشه:


1)gradiant decent -> requires_grad = True




2)backpropagation

In [6]:
class LinearRegreesionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1,
                                requires_grad=True,
                                dtype=torch.float))
    self.bias = nn.Parameter(torch.randn(1,
                                requires_grad=True,
                                dtype=torch.float))
  def forward(self,x: torch.tensor) -> torch.Tensor:
    return self.weights * x + self.bias

In [7]:
#create random seed
torch.manual_seed(42) #baraye random number ha
model_0 = LinearRegreesionModel()

#check kardan parametr ha
list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [8]:
model_0.state_dict()


OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [9]:
#make predictions
with torch.inference_mode():
  y_pred = model_0(X_test)

y_pred

tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]])

In [10]:
#setup loss function
ls = nn.L1Loss()


#setup optimizer
op = torch.optim.SGD(model_0.parameters(),lr=0.01)

Builidng a training loop

In [11]:
torch.manual_seed(42)

epochs = 100 # one loop through the data
for epoch in range(epochs):
  #set the model to train


  model_0.train() #train mode in pytorch


  #1) forward pass

  y_pred = model_0(X_train)

  #2) calculate loss function

  loss = ls(y_pred,y_train)
  print(f"loss:", loss)

  #3) optimizer zero gard

  op.zero_grad()

  #4) backpropagation

  loss.backward()

  #5) step the optimizer ( gradiant decent)

  op.step()

  #Testing

  model_0.eval()
  with torch.inference_mode():# turn off gradian tracking

  #1)do the forward pass

    test_pre = model_0(X_test)

  #2) calculate the loss

    test_loss = ls(test_pre,y_test)

  #3)


loss: tensor(0.3129, grad_fn=<MeanBackward0>)
loss: tensor(0.3014, grad_fn=<MeanBackward0>)
loss: tensor(0.2898, grad_fn=<MeanBackward0>)
loss: tensor(0.2783, grad_fn=<MeanBackward0>)
loss: tensor(0.2668, grad_fn=<MeanBackward0>)
loss: tensor(0.2553, grad_fn=<MeanBackward0>)
loss: tensor(0.2438, grad_fn=<MeanBackward0>)
loss: tensor(0.2322, grad_fn=<MeanBackward0>)
loss: tensor(0.2207, grad_fn=<MeanBackward0>)
loss: tensor(0.2092, grad_fn=<MeanBackward0>)
loss: tensor(0.1977, grad_fn=<MeanBackward0>)
loss: tensor(0.1862, grad_fn=<MeanBackward0>)
loss: tensor(0.1746, grad_fn=<MeanBackward0>)
loss: tensor(0.1631, grad_fn=<MeanBackward0>)
loss: tensor(0.1516, grad_fn=<MeanBackward0>)
loss: tensor(0.1401, grad_fn=<MeanBackward0>)
loss: tensor(0.1285, grad_fn=<MeanBackward0>)
loss: tensor(0.1170, grad_fn=<MeanBackward0>)
loss: tensor(0.1061, grad_fn=<MeanBackward0>)
loss: tensor(0.0968, grad_fn=<MeanBackward0>)
loss: tensor(0.0891, grad_fn=<MeanBackward0>)
loss: tensor(0.0823, grad_fn=<Mean

In [12]:


model_0.state_dict()

OrderedDict([('weights', tensor([0.5784])), ('bias', tensor([0.3513]))])

Saving the Model

In [14]:
from pathlib import Path

# 1) create directory

model_path = Path("models")
model_path.mkdir(parents=True , exist_ok=True)

# 2) create model path save

model_name =  'first_model_LiniearRegression.pth'
model_save_path = model_path / model_name

# 3) save the model
print(f'Saving model to: {model_save_path}')
torch.save(obj=model_0.state_dict(),
           f=model_save_path)


Saving model to: models/first_model_LiniearRegression.pth


Put it all together

In [15]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt


In [16]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

Data

In [18]:
#create data using linear regression formula
weight = 0.7
bias = 0.3

#create range
start = 0
end = 1
step = 0.02

#create x and y
X = torch.arange(start,end,step).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [20]:
#spilit data to train and test
train_spilit = int(0.8 * len(X))
X_train , y_train =  X[:train_spilit] , y[:train_spilit]
X_test , y_test = X[train_spilit:] , y[train_spilit:]
len(X_train),len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

Build a Linear Regression Model


In [21]:
#build the class
class LinearRegressionModelV2(nn.Module):
  def __init__(self):
    super().__init__()

    self.linear_layer = nn.Linear(in_features=1,
                                  out_features=1)

  def forward(self, x : torch.Tensor) -> torch.Tensor:
    return self.linear_layer(x)

torch.manual_seed(42)
model_1 = LinearRegressionModelV2()
model_1 , model_1.state_dict()

(LinearRegressionModelV2(
   (linear_layer): Linear(in_features=1, out_features=1, bias=True)
 ),
 OrderedDict([('linear_layer.weight', tensor([[0.7645]])),
              ('linear_layer.bias', tensor([0.8300]))]))

training

In [ ]:
for training we need:
1) loss function
2) optimizer
3) training loop
4) testing loop

In [24]:
#setuo loss functions
loss = nn.L1Loss()

#setup optimizer
op = torch.optim.SGD(params=model_1.parameters(),lr=0.01)

In [26]:
#traning loop

torch.manual_seed(42)
epochs = 200

for epoch in range(epochs):

  #step 0
  model_1.train()

  #step 1: forward pass
  y_pred = model_1(X_train)

  #step 2 : loss
  ls = loss(y_pred , y_train)

  #step 3 : optimizer zero grad
  op.zero_grad()

  #step 4: backpropagation
  ls.backward()

  #step 5: optimizer
  op.step()


  #Testing
  model_1.eval()
  with torch.inference_mode():
    test_pred = model_1(X_test)

    test_loss = loss(test_pred , y_test)

  if epoch % 10 == 0:
    print(f'epoch : {epoch} | loss :  {ls} | test_loss : {test_loss}' )

epoch : 0 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 10 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 20 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 30 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 40 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 50 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 60 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 70 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 80 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 90 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 100 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 110 | loss :  0.0012645035749301314 | test_loss : 0.013801807537674904
epoch : 120 | loss :  0.0012645035749301314 | test_loss : 0.013

Save and Load Data

In [ ]:
from pathlib import path
model_path = path("model")
model_path.mkdir(parent=True, exist_ok=True)

